In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('merged_data.csv')

df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,1,credit_card,1,18.12,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,3,voucher,1,2.00,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,2,voucher,1,18.59,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,1,boleto,1,141.46,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,1,credit_card,3,179.12,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117324,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,1,credit_card,3,195.00,29bb71b2760d0f876dfa178a76bc4734,4,NaN,So uma peça que veio rachado mas tudo bem rs,2018-03-01 00:00:00,2018-03-02 17:50:01
117325,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1,b80910977a37536adeddd63663f916ad,...,1,credit_card,5,271.01,371579771219f6db2d830d50805977bb,5,NaN,Foi entregue antes do prazo.,2017-09-22 00:00:00,2017-09-22 23:10:57
117326,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1,d1c427060a0f73f6b889a5c7c61f2ac4,...,1,credit_card,4,441.16,8ab6855b9fe9b812cd03a480a25058a1,2,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56
117327,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2,d1c427060a0f73f6b889a5c7c61f2ac4,...,1,credit_card,4,441.16,8ab6855b9fe9b812cd03a480a25058a1,2,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56
117328,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1,006619bbed68b000c8ba3f8725d5409e,...,1,debit_card,1,86.86,dc9c59b4688062c25758c2be4cafc523,5,NaN,NaN,2018-03-17 00:00:00,2018-03-17 16:33:31

In [3]:
df["customer_id"].nunique()

97916

In [4]:
single_order_clients = df.groupby('customer_unique_id').filter(lambda x: len(x) == 1)
single_order_clients

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,1,boleto,1,141.46,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,1,credit_card,3,179.12,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58
5,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1,d0b61bfb1de832b15ba9d266ca96e5b0,...,1,credit_card,1,72.20,359d03e676b3c069f62cadba8dd3f6e8,5,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03 00:00:00,2017-12-05 19:21:58
6,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1,65266b2da20d04dbe00c5c2d3bb7859e,...,1,credit_card,1,28.62,e50934924e227544ba8246aeb3770dd4,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 13:02:51
7,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00,1,060cb19345d90064d1015407193c233d,...,1,credit_card,6,175.26,89b738e70a1ce346db29a20fb2910161,4,NaN,NaN,2017-07-27 00:00:00,2017-07-27 22:48:30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117322,880675dff2150932f1601e1c07eadeeb,47cd45a6ac7b9fb16537df2ccffeb5ac,delivered,2017-02-23 09:05:12,2017-02-23 09:15:11,2017-03-01 10:22:52,2017-03-06 11:08:08,2017-03-22 00:00:00,1,ea73128566d1b082e5101ce46f8107c7,...,1,credit_card,3,155.99,96e8f371a3983122b739944537e15525,5,NaN,NaN,2017-03-07 00:00:00,2017-03-11 15:42:41
117323,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,1,ac35486adb7b02598c182c2ff2e05254,...,1,credit_card,3,85.08,e262b3f92d1ce917aa412a9406cf61a6,5,NaN,NaN,2017-03-22 00:00:00,2017-03-23 11:02:08
117324,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,1,credit_card,3,195.00,29bb71b2760d0f876dfa178a76bc4734,4,NaN,So uma peça que veio rachado mas tudo bem rs,2018-03-01 00:00:00,2018-03-02 17:50:01
117325,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1,b80910977a37536adeddd63663f916ad,...,1,credit_card,5,271.01,371579771219f6db2d830d50805977bb,5,NaN,Foi entregue antes do prazo.,2017-09-22 00:00:00,2017-09-22 23:10:57
117328,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1,006619bbed68b000c8ba3f8725d5409e,...,1,debit_card,1,86.86,dc9c59b4688062c25758c2be4cafc523,5,NaN,NaN,2018-03-17 00:00:00,2018-03-17 16:33:31

In [5]:
import datetime as dt

df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])


df["order_approved_at"] = pd.to_datetime(df["order_approved_at"])
current_date = max(df["order_approved_at"])

rfm = df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (current_date - x.max()).days,
    'order_id': 'count',
    'payment_value': 'sum'
}).reset_index()


rfm.columns = ['customer_unique_id', 'Recency', 'Frequency', 'Monetary']

rfm.head()

                 customer_unique_id  Recency  Frequency  Monetary
0  0000366f3b9a7992bf8c76cfdf3221e2      116          1    141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f      119          1     27.19
2  0000f46a3911fa3c0805444483337064      541          1     86.22
3  0000f6ccb0745a6a4b88665a16c9f078      325          1     43.62
4  0004aac84e0df4da2b147fca70cf8255      292          1    196.89

In [6]:
rfm.sort_values("Monetary")

                     customer_unique_id  Recency  Frequency   Monetary
18389  317cfc692e3f86c45c95697c61c853a6        8          2       9.59
70055  bd06ce0e06ad77a7f681f1a4960a3cc6      354          1      10.07
66435  b33336f46234b24a613ad9064d13106d       73          1      10.89
15032  2878e5b88167faab17d4fb83a986d38b      308          1      11.63
41308  6f5b9d1cdccc4d28f0483a612edecacf      366          1      11.63
...                                 ...      ...        ...        ...
43827  763c8b1c9c68a0229c42c9fc6f662b93       50          4   29099.52
88713  ef8d54b3797ea4db1d63f0ced6a906e9      137         10   30186.00
23774  4007669dec559734d6f53e029e360987      283          6   36489.24
72628  c402f431464c72e27330a67f7b94d4fb      193         20   44048.00
3775   0a0a92112bd4c708ca5fde585afaa872      339          8  109312.64

[94720 rows x 4 columns]

In [7]:
rfm["RecencyScore"] = pd.qcut(rfm['Recency'], 4, ['1', '2', '3', '4'])
rfm["FrequencyScore"] = pd.qcut(rfm['Frequency'].rank(method="first"), 4, ['4', '3', '2', '1'])
rfm["MonetaryScore"] = pd.qcut(rfm['Monetary'], 4, ['4', '3', '2', '1'])



rfm["RFM"] = rfm["RecencyScore"].astype(str) + rfm["FrequencyScore"].astype(str) + rfm["MonetaryScore"].astype(str)

rfm["RFM_SCORE"] = rfm["RecencyScore"].astype(int) + rfm["FrequencyScore"].astype(int) + rfm["MonetaryScore"].astype(int)

rfm["Segment"] = pd.qcut(
    rfm["RFM_SCORE"], 
    q=[0, 0.04, 0.25, 0.5, 0.75, 1],
    labels=["VIP", "TBC", "BC", "CC", "Other"],
    duplicates="drop"
)

segment_distribution = rfm["Segment"].value_counts()
print(segment_distribution)

Segment
BC       32879
TBC      22348
Other    16567
CC       14878
VIP       8048
Name: count, dtype: int64

In [8]:
df["Customer Segment"] = df["customer_unique_id"].map(rfm.set_index("customer_unique_id")["Segment"])

In [9]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,Customer Segment
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,credit_card,1,18.12,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,BC
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,voucher,1,2.00,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,BC
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,voucher,1,18.59,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,BC
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,boleto,1,141.46,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,TBC
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,credit_card,3,179.12,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,BC

In [10]:
df['customer_mean_review_score'] = df['customer_unique_id'].map(df.groupby('customer_unique_id')['review_score'].mean())

In [ ]:
df["Unhappy"] = (df["Customer Segment"] == "VIP") & (df["order_purchase_timestamp"] > current_date - dt.timedelta(days=30)) & (df["review_score"] < df ["customer_mean_review_score"])

df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,Customer Segment,customer_mean_review_score,Unhappy
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,18.12,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,BC,4.25,False
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,2.00,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,BC,4.25,False
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,18.59,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,BC,4.25,False
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,141.46,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,TBC,4.00,False
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,179.12,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,BC,5.00,False

In [12]:
df[df["Unhappy"]==True]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,Customer Segment,customer_mean_review_score,Unhappy
3770,78d7bf360bb60d0dd4bd37663c126524,bbfd6562ad0326487d9e5c8e6433fc8d,delivered,2018-08-26 13:23:23,2018-08-26 13:35:09,2018-08-27 15:12:00,2018-08-30 23:40:54,2018-09-10 00:00:00,1,71b7bb7d435217ef96c1ec8e48421599,...,188.89,d8b70c5af2fc6f0173b87314a7d7ce56,1,NaN,NaN,2018-08-31 00:00:00,2018-09-03 15:02:23,VIP,3.000000,True
10620,e339c040755b354d17a122b68617cb4f,511a4d0fd15ef186a3103e38ef910563,delivered,2018-08-16 11:54:27,2018-08-16 12:10:13,2018-08-20 13:49:00,2018-08-28 00:12:31,2018-09-18 00:00:00,1,675dbd52c3dadeafa9a8c96ea5a9bfc6,...,177.25,013790829ce3ff85c43327d680bfaadd,4,NaN,NaN,2018-08-29 00:00:00,2018-08-30 23:54:08,VIP,4.500000,True
10773,1b9411e11370aedecc0bb2daa7f41501,300b04fccf49393ab58606cdf2c4ce52,delivered,2018-08-17 16:11:01,2018-08-17 16:29:56,2018-08-23 14:08:00,2018-08-27 17:19:02,2018-09-06 00:00:00,1,d78c524a16fe960ae8229034d4541469,...,110.77,c5cdc9882ed59900426e8e31db007c68,1,NaN,NaN,2018-08-28 00:00:00,2018-08-29 13:50:46,VIP,2.500000,True
12473,4d14cee530bddf889464f788f5cde498,8c0b305bd4a7d01a811b4ab3f1f72cd7,delivered,2018-08-13 14:44:16,2018-08-13 14:55:24,2018-08-15 12:49:00,2018-08-18 16:54:44,2018-08-20 00:00:00,1,b3cde9c63f334490ef1c3348bb7dfc3c,...,32.43,f7f21e4ae2e2258af84edeb9b8fad16e,4,NaN,NaN,2018-08-19 00:00:00,2018-08-22 17:03:04,VIP,4.750000,True
28346,05f8021cf7217f1990addecad0e24b7a,1b4f0369610bd9e4d237aab3a993bdcd,delivered,2018-08-10 20:50:51,2018-08-10 21:04:25,2018-08-22 14:49:00,2018-08-28 13:08:52,2018-09-11 00:00:00,1,d670c0f6be30a062ebd8f8612ea82d71,...,198.25,c8cb9544919164f774315c60d131d76b,4,NaN,NaN,2018-08-29 00:00:00,2018-08-29 16:50:27,VIP,4.666667,True
39820,05ec9565bccc292561dec1d33bfefdfa,928194af995122dd13f29b05cedc6a68,delivered,2018-08-05 11:15:46,2018-08-05 11:30:16,2018-08-07 10:34:00,2018-08-10 19:12:12,2018-08-15 00:00:00,1,8dc8cdb4e5a2d2f2af019bc5a255e907,...,62.92,1499b9bdfc9383ca49ffd56181065912,3,Recomendo,Ok,2018-08-11 00:00:00,2018-08-11 22:39:46,VIP,3.200000,True
45116,e51a9885ddaf8cc8e4a5f760fa7992bb,3dcbd63311cf3959c5a02ad4a923b714,delivered,2018-08-06 21:13:55,2018-08-06 21:25:19,2018-08-07 13:31:00,2018-08-18 00:21:53,2018-09-06 00:00:00,1,092eff69a9499b052a2258f502ea0775,...,62.11,1b2284f7058c285644fffeb17b531b05,1,NaN,NaN,2018-08-19 00:00:00,2018-08-21 02:20:12,VIP,3.000000,True
45712,d2a447028b1fbbc9200739e3fee4e22c,b0dbe26f4e6b3d6dfe331c70f7e2073e,delivered,2018-08-15 14:57:55,2018-08-15 20:29:49,2018-08-17 15:21:00,2018-08-21 21:14:58,2018-08-24 00:00:00,1,db580783a754f97648c304e049cf4d76,...,62.11,b7900db6a66c2cd86cae67aeabe60f83,4,NaN,NaN,2018-08-22 00:00:00,2018-08-25 12:26:57,VIP,4.500000,True
45757,b18f96d97651133bd9a491945fa1d3bd,e342cc220c9ce03ad61939a23e6571fd,delivered,2018-08-28 10:57:13,2018-08-28 11:10:23,2018-08-28 15:26:00,2018-08-30 17:42:23,2018-08-31 00:00:00,1,3207053643b68f43eed19750c0ad8157,...,38.37,e7c79828cc26249cb387b63b77a96199,3,NaN,NaN,2018-08-31 00:00:00,2018-09-03 10:05:02,VIP,4.250000,True
49309,e98eaa3acbf55a63a501cec1baf45f9e,f863f99cff7c8ec08708df2fb890dd6f,delivered,2018-08-20 12:38:56,2018-08-20 15:36:01,2018-08-22 13:10:00,2018-08-30 21:28:48,2018-09-03 00:00:00,1,d6183bc1d858bac539ee14cd72203b06,...,674.69,54afe5c8186fb4b06c1bdded93a22c83,1,NaN,NaN,2018-08-31 00:00:00,2018-09-16 04:32:45,VIP,3.000000,True
59256,1e61c2d93012f7a32fe86de9bafc3a1f,bbacd4a4139f37ae3aedcc0f1e4d86eb,delivered,2018-08-09 22:37:32,2018-08-09 22:50:09,2018-08-10 14:46:00,2018-08-15 11:33:55,2018-08-21 00:00:00,1,a1e903cd2d23763ef8b85ec12eb79d9c,...,65.43,f2f23f3393d55628add43207955c1c5c,4,Recomendo,NaN,2018-08-16 00:00:00,2018-08-16 17:37:22,VIP,4.500000,True
60033,58af2a09b442a8b28f672e56ad7154b5,3978b77bddb2776390f38dfa186891d3,delivered,2018-08-09 19:29:02,2018-08-09 19:44:49,2018-08-10 13:06:00,2018-08-11 21:38:48,2018-08-16 00:00:00,1,63ddf5df9f36e2fb2fc11b3894222c31,...,47.58,791c0943eb02020656435638f4e06a32,4,NaN,NaN,2018-08-12 00:00:00,2018-08-13 13:04:48,VIP,4.333333,True
60034,58af2a09b442a8b28f672e56ad7154b5,3978b77bddb2776390f38dfa186891d3,delivered,2018-08-09 19:29:02,2018-08-09 19:44:49,2018-08-10 13:06:00,2018-08-11 21:38:48,2018-08-16 00:00:00,2,63ddf5df9f36e2fb2fc11b3894222c31,...,47.58,791c0943eb02020656435638f4e06a32,4,NaN,NaN,2018-08-12 00:00:00,2018-08-13 13:04:48,VIP,4.333333,True
65276,f3ee55bf50ef2f2318599425ef80107d,828a9b9f129a8b103ad146559a75d4c6,delivered,2018-08-17 16:53:17,2018-08-17 17:09:40,2018-08-21 13:57:00,2018-08-28 17:24:48,2018-09-04 00:00:00,1,12728f215b3381cac22b1fba7a97f5cf,...,60.25,dd43a798c9e8baf7b69297bb076c517d,4,NaN,NaN,2018-08-29 00:00:00,2018-08-29 21:58:35,VIP,4.333333,True
66309,57bc9b432f93fd30a3cc83952ccbf267,7022a8efc480a54d4fcaddb10315fa3a,delivered,2018-08-25 11:01:56,2018-08-25 11:15:09,2018-08-27 12:16:00,2018-08-29 15:38:59,2018-09-05 00:00:00,1,c4baedd846ed09b85f78a781b522f126,...,113.61,40dfbbee12ddf47907c962270d975ede,4,NaN,NaN,2018-08-30 00:00:00,2018-08-31 15:01:38,VIP,4.500000,True
70016,cd5343ffb012a7157ddbcf5720100c01,c6ae270b58b4692321a73aa741d183af,delivered,2018-08-26 12:38:57,2018-08-26 12:50:18,2018-08-27 14:18:00,2018-08-30 14:38:54,2018-09-11 00:00:00,1,54f45413afc0d5480c59f5dfeed2d19f,...,336.16,05d3874965dd1ba4330bab86c5fff9aa,1,Produto faltando,Fiz o pedido de dois kits de progressiva e só ...,2018-08-31 00:00:00,2018-09-02 14:08:54,VIP,1.666667,True
70017,cd5343ffb012a7157ddbcf5720100c01,c6ae270b58b4692321a73aa741d183af,delivered,2018-08-26 12:38:57,2018-08-26 12:50:18,2018-08-27 14:18:00,2018-08-30 14:38:54,2018-09-11 00:00:00,2,54f45413afc0d5480c59f5dfeed2d19f,...,336.16,05d3874965dd1ba4330bab86c5fff9aa,1,Produto faltando,Fiz o pedido de dois kits de progressiva e só ...,2018-08-31 00:00:00,2018-09-02 14:08:54,VIP,1.666667,True
73020,8a27647dc5f71b1eda4620983e89334c,a4f88a770cb2bd3e167bbec6264e7e3d,delivered,2018-08-16 16:05:01,2018-08-16 16:15:18,2018-08-17 14:49:00,2018-08-28 16:07:32,2018-09-04 00:00:00,1,683958673970508a3486126e91125b56,...,130.88,61d4af830a5bd7e158a33844f9ea74cf,4,Recomendo muito bom,NaN,2018-08-29 00:00:00,2018-08-30 11:14:33,VIP,4.500000,True
75859,6e10384d6572f58ba12c848b91299f39,a089bc5d8035937e139d790de9b24e76,delivered,2018-08-20 23:18:27,2018-08-20 23:30:18,2018-08-21 11:40:00,2018-08-30 21:32:06,2018-09-17 00:00:00,1,c1b63d4c57e9d56a827fdb72afeaa246,...,133.62,14cbabf3490837a3af22eb045eed5f40,3,não recebi um produto,comprei uma garrafa térmica e uma capa de colc...,2018-08-31 00:00:00,2018-09-01 14:34:07,VIP,4.000000,True
75860,6e10384d6572f58ba12c848b91299f39,a089bc5d8035937e139d790de9b24e76,delivered,2018-08-20 23:18:27,2018-08-20 23:30:18,2018-08-21 11:40:00,2018-08-30 21:32:06,2018-09-17 00:00:00,2,683647534fe73616ae97d91a6ef253f4,...,133.62,14cbabf3490837a3af22eb045eed5f40,3,não recebi um produto,comprei uma garrafa térmica e uma capa de colc...,2018-08-31 00:00:00,2018-09-01 14:34:07,VIP,4.000000,True
76999,1d911134e95ec6f299e80fe19b5b88c5,4dfe57404141dbca39b1eae2ec077e78,canceled,2018-08-05 22:27:23,2018-08-05 22:35:17,NaN,NaN,2018-08-28 00:00:00,1,cb9d764f38ee4d0c00af64d5c388f837,...,50.24,e97be4601a6fa63ed4bb9f20a944a396,1,NaN,Sempre comprei na americas.com e os pedidos ch...,2018-08-30 00:00:00,2018-08-30 11:39:13,VIP,3.000000,True
85843,a77696c7b42da1121205a92ddae7b5c7,93b888a330b974d20e5e75eecbb3c6d0,delivered,2018-08-10 12:09:09,2018-08-10 12:24:53,2018-08-13 14:52:00,2018-08-14 20:08:59,2018-08-23 00:00:00,1,3fc3d637781e5d185455013606a6e2cd,...,40.35,772d1fdeb559346a53435efac02ef805,3,NaN,"produto não atende a sua finalidade, pois não ...",2018-08-15 00:00:00,2018-08-16 09:26:23,VIP,3.500000,True
88728,75fd71aadc94da494ae8e9010c38d4d1,74db498590882c1bc2a01aebb32d7bb0,delivered,2018-08-17 11:12:26,2018-08-17 11:29:21,2018-08-21 12:54:00,2018-08-27 16:11:50,2018-09-05 00:00:00,1,6d0d465294cd2cb44aea084f34405967,...,250.32,8a2b18a24d18a8df014914001771abc2,4,10,Rápido,2018-08-28 00:00:00,2018-08-28 21:09:30,VIP,4.500000,True
92682,ccd2795b4fd33757b039fb15b8a12109,e21e09c974438b29525fc0e318648258,delivered,2018-08-15 16:58:08,2018-08-15 17:10:16,2018-08-16 14:27:00,2018-08-17 22:51:29,2018-08-28 00:00:00,1,3e00f726a0e1eab8f2ae5137bf9bf54a,...,86.04,d5613f8675ad0c3eaf8a36d49de0f472,3,Ainda nao recebi o produt,Ainda nao recebi o banquinho. Quanto aos cober...,2018-08-18 00:00:00,2018-08-21 10:10:34,VIP,3.400000,True
92683,ccd2795b4fd33757b039fb15b8a12109,e21e09c974438b29525fc0e318648258,delivered,2018-08-15 16:58:08,2018-08-15 17:10:16,2018-08-16 14:27:00,2018-08-17 22:51:29,2018-08-28 00:00:00,2,9fe67dbcc33795d7fafe354d7c850115,...,86.04,d5613f8675ad0c3eaf8a36d49de0f472,3,Ainda nao recebi o produt,Ainda nao recebi o banquinho. Quanto aos cober...,2018-08-18 00:00:00,2018-08-21 10:10:34,VIP,3.400000,True
92684,ccd2795b4fd33757b039fb15b8a12109,e21e09c974438b29525fc0e318648258,delivered,2018-08-15 16:58:08,2018-08-15 17:10:16,2018-08-16 14:27:00,2018-08-17 22:51:29,2018-08-28 00:00:00,3,9fe67dbcc33795d7fafe354d7c850115,...,86.04,d5613f8675ad0c3eaf8a36d49de0f472,3,Ainda nao recebi o produt,Ainda nao recebi o banquinho. Quanto aos cober...,2018-08-18 00:00:00,2018-08-21 10:10:34,VIP,3.400000,True
92685,ccd2795b4fd33757b039fb15b8a12109,e21e09c974438b29525fc0e318648258,delivered,2018-08-15 16:58:08,2018-08-15 17:10:16,2018-08-16 14:27:00,2018-08-17 22:51:29,2018-08-28 00:00:00,4,9fe67dbcc33795d7fafe354d7c850115,...,86.04,d5613f8675ad0c3eaf8a36d49de0f472,3,Ainda nao recebi o produt,Ainda nao recebi o banquinho. Quanto aos cober...,2018-08-18 00:00:00,2018-08-21 10:10:34,VIP,3.400000,True
111379,1b18059100e6796d8551306a1876fc09,0c7ba0b11923d9c8bad61bfdcd6b3b2b,delivered,2018-08-13 12:22:49,2018-08-13 12:35:10,2018-08-15 11:30:00,2018-08-16 18:38:40,2018-08-20 00:00:00,1,20545c8a1fb497b7e692794159e7afdb,...,21.28,1c4080ec54a4084749b99079b2b56547,4,Muito bom,NaN,2018-08-17 00:00:00,2018-08-17 22:41:54,VIP,4.250000,True
113863,ef22458e7cfa237cd68b3be657f4f0c8,5e1ec1ba98bb8ce60763eb2d21560346,delivered,2018-08-17 16:53:17,2018-08-17 17:09:37,2018-08-21 13:57:00,2018-08-28 15:25:45,2018-09-04 00:00:00,1,12728f215b3381cac22b1fba7a97f5cf,...,60.25,dd43a798c9e8baf7b69297bb076c517d,4,NaN,NaN,2018-08-29 00:00:00,2018-08-29 21:58:35,VIP,4.333333,True

In [14]:
unhappy_vip = df[df["Unhappy"]==True]

In [15]:
unhappy_vip[['customer_unique_id', 'order_purchase_timestamp', 'review_score', 'customer_mean_review_score', 'Customer Segment']].head()

,customer_unique_id,order_purchase_timestamp,review_score,customer_mean_review_score,Customer Segment
3770,52b8fc428690f8974a3d3ff3a162f7b7,2018-08-26 13:23:23,1,3.000000,VIP
10620,cde6577300fbd06655ff162902f15b2a,2018-08-16 11:54:27,4,4.500000,VIP
10773,8d187f36fa18c60c2ac49e7a966d8ff7,2018-08-17 16:11:01,1,2.500000,VIP
12473,ad7fda75731aed4991eb80d939db8115,2018-08-13 14:44:16,4,4.750000,VIP
28346,5d63628c95182301765aa1482b0293aa,2018-08-10 20:50:51,4,4.666667,VIP

In [16]:
unhappy_vip.to_csv("unhappy_vip.csv", index=False)